debug: false

logging.level:
  io.pivotal.dmfrey: DEBUG

management.endpoints.web.expose: health, info, env, metrics

server:
  port: ${PORT:9082}
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      write_dates_as_timestamps: false

  cloud:
    stream:
      bindings:
        output:
          destination: board-event-notifications
          contentType: application/json
          producer:
            headerMode: raw # Outbound data has no embedded headers

---
spring:
  profiles: cloud

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update